"""Miscellaneous advice not otherwise categorized."""
# TODO: why are these not in _root of check-dir?

from proselint.checks.misc import (
    apologizing,
    back_formations,
    braces,
    but,
    capitalization,
    composition,
    currency,
    debased,
    greylist,
    illogic,
    inferior_superior,
    institution_name,
    latin,
    many_a,
    metadiscourse,
    monotonic,
    narcissism,
    not_guilty,
    numbers,
    phrasal_adjectives,
    plurals,
    preferred_forms,
    pretension,
    professions,
    scare_quotes,
    suddenly,
    tense_present,
    waxed,
    whence,
)

__register__ = (
    *apologizing.__register__,
    *back_formations.__register__,
    *braces.__register__,
    *but.__register__,
    *capitalization.__register__,
    *composition.__register__,
    *currency.__register__,
    *debased.__register__,
    *greylist.__register__,
    *illogic.__register__,
    *inferior_superior.__register__,
    *institution_name.__register__,
    *latin.__register__,
    *many_a.__register__,
    *metadiscourse.__register__,
    *monotonic.__register__,
    *narcissism.__register__,
    *not_guilty.__register__,
    *numbers.__register__,
    *phrasal_adjectives.__register__,
    *plurals.__register__,
    *preferred_forms.__register__,
    *pretension.__register__,
    *professions.__register__,
    *scare_quotes.__register__,
    *suddenly.__register__,
    *tense_present.__register__,
    *waxed.__register__,
    *whence.__register__,
)
