# -*- coding: utf-8 -*-
"""MAU102: Needless variants.

---
layout:     post
error_code: MAU102
source:     Garner's Modern American Usage
source_url: http://amzn.to/15wF76r
title:      needless variants
date:       2014-06-10 12:31:19
categories: writing
---

Points out use of needless variants.

"""
from proselint.tools import memoize, preferred_forms_check


@memoize
def check(blob):
    """Suggest the preferred forms."""
    err = "MAU102"
    msg = "Needless variant. '{}' is the preferred form."

    preferences = [

        # Needless variants
        ["abolition",         ["abolishment"]],
        ["accessory",         ["accessary"]],
        ["accrual",           ["accruement"]],
        ["accumulate",        ["cumulate"]],
        ["accused",           ["accusee"]],
        ["acquaintance",      ["acquaintanceship"]],
        ["acquittal",         ["acquitment"]],
        ["administer",        ["administrate"]],
        ["administered",      ["administrated"]],
        ["administering",     ["administrating"]],
        ["adulterous",        ["adulterate"]],
        ["advisory",          ["advisatory"]],
        ["advocate",          ["advocator"]],
        ["alleger",           ["allegator"]],
        ["allusive",          ["allusory"]],
        ["ameliorate",        ["meliorate"]],
        ["amorous",           ["amative"]],
        ["amortization",      ["amortizement"]],
        ["amphibology",       ["amphiboly"]],
        ["anachronism",       ["parachronism"]],
        ["anecdotist",        ["anecdotalist"]],
        ["anilingus",         ["anilinctus"]],
        ["anticipatory",      ["anticipative"]],
        ["buck naked",        ["butt naked"]],
        ["catch fire",        ["catch on fire"]],
        ["ceasefire",         ["cease fire"]],
        ["cellphone",         ["cell phone", "cell-phone"]],
        ["cigarette",         ["cigaret"]],
        ["collodion",         ["collodium"]],
        ["collusive",         ["collusory"]],
        ["convertible",       ["conversible"]],
        ["endow",             ["indow"]],
        ["enigmas",           ["enigmatas"]],
        ["expedient",         ["expediential"]],
        ["eyeing",            ["eying"]],
        ["henceforth",        ["henceforward"]],
        ["hesitancy",         ["hesitance"]],
        ["heterogeneous",     ["heterogenous"]],
        ["hierarchical",      ["hierarchic"]],
        ["hindmost",          ["hindermost"]],
        ["honoree",           ["honorand"]],
        ["hypostatize",       ["hypostasize"]],
        ["hysterical",        ["hysteric"]],
        ["idolize",           ["idolatrize"]],
        ["impersonation",     ["personation"]],
        ["impervious",        ["imperviable"]],
        ["importunity",       ["importunacy"]],
        ["impotence",         ["impotency"]],
        ["imprimatur",        ["imprimatura"]],
        ["incitement",        ["incitation"]],
        ["inconsistency",     ["inconsistence"]],
        ["incriminate",       ["criminate"]],
        ["incurrence",        ["incurment"]],
        ["infrequent",        ["unfrequent"]],
        ["inhibitory",        ["inhibitive"]],
        ["innovative",        ["innovational"]],
        ["inquisitorial",     ["inquisitional"]],
        ["insistence",        ["insistment"]],
        ["instillation",      ["instillment"]],
        ["instinctive",       ["instinctual"]],
        ["insubstantial",     ["unsubstantial"]],
        ["insurer",           ["insuror"]],
        ["insurrectionary",   ["insurrectional"]],
        ["interpret",         ["interpretate"]],
        ["intervention",      ["intervenience"]],
        ["ironic",            ["ironical"]],
        ["irrevocable",       ["unrevokable"]],
        ["judgmental",        ["judgmatic"]],
        ["jury-rigged",       ["jerry-rigged"]],
        ["jury-rigged",       ["gerry-rigged"]],
        ["kaffeeklatsch",     ["Coffee klatsch", "coffee klatch"]],
        ["knickknack",        ["nicknack"]],
        ["labyrinthine",      ["labyrinthian"]],
        ["laudatory",         ["laudative"]],
        ["legitimize",        ["legitimatize"]],
        ["legitimation",      ["legitimatization"]],
        ["legitimation",      ["legitimization"]],
        ["lengthwise",        ["lengthways"]],
        ["life-size",         ["life-sized"]],
        ["lithe",             ["lithesome"]],
        ["loath",             ["loth"]],
        ["lubricious",        ["lubricous"]],
        ["mayhem",            ["maihem"]],
        ["medical marijuana", ["medicinal marijuana"]],
        ["minimize",          ["minimalize"]],
        ["monetize",          ["monetarize"]],
        ["movable",           ["moveable"]],
        ["murk",              ["mirk"]],
        ["murky",             ["mirky"]],
        ["narcissism",        ["narcism"]],
        ["neglectful",        ["neglective"]],
        ["negligence",        ["negligency"]],
        ["neologist",         ["neologizer"]],
        ["neurological",      ["neurologic"]],
        ["nictitate",         ["nictate"]],
        ["normality",         ["normalcy"]],
        ["numbness",          ["numbedness"]],
        ["omissible",         ["omittable"]],
        ["onomatopoeic",      ["onomatopoetic"]],
        ["opined",            ["opinioned"]],
        ["optimal advantage", ["optimum advantage"]],
        ["orient",            ["orientate"]],
        ["disoriented",       ["disorientated"]],
        ["outsize",           ["outsized"]],
        ["oversize",          ["oversized"]],
        ["overthrow",         ["overthrowal"]],
        ["pacifist",          ["pacificist"]],
        ["participatory",     ["participative"]],
        ["parti-colored",     ["parti-color"]],
        ["parti-colored",     ["party-colored"]],
        ["patina",            ["patine"]],
        ["password",          ["passcode"]],
        ["pediatrician",      ["pediatrist"]],
        ["pederast",          ["paederast"]],
        ["penumbral",         ["penumbrous"]],
        ["pejorative",        ["perjorative"]],
        ["permute",           ["permutate"]],
        ["permissive",        ["permissory"]],
        ["pharmaceutical",    ["pharmaceutic"]],
        ["pleurisy",          ["pleuritis"]],
        ["policyholder",      ["policy holder"]],
        ["policyholder",      ["policyowner"]],
        ["politicize",        ["politicalize"]],
        ["pre-Columbian",     ["precolumbian"]],
        ["precedence",        ["precedency"]],
        ["preceptorial",      ["preceptoral"]],
        ["precipitancy",      ["precipitance"]],
        ["precipitate",       ["precipitant"]],
        ["preclusive",        ["preclusory"]],
        ["prefectorial",      ["prefectoral"]],
        ["preponderantly",    ["preponderately"]],
        ["preservation",      ["preserval"]],
        ["preventive",        ["preventative"]],
        ["proconsulate",      ["proconsulship"]],
        ["procreative",       ["procreational"]],
        ["procurement",       ["procurance"]],
        ["propulsion",        ["propelment"]],
        ["prosecutory",       ["prosecutive"]],
        ["protective",        ["protectory"]],
        ["provocative",       ["provocatory"]],
        ["prurience",         ["pruriency"]],
        ["psychical",         ["psychal"]],
        ["punitive",          ["punitory"]],
        ["pygmy",             ["pygmean", "pygmaen"]],
        ["quantify",          ["quantitate"]],
        ["questionnaire",     ["questionary"]],
        ["quiescence",        ["quiescency"]],
        ["rabbi",             ["rabbin"]],
        ["reasonableness",    ["reasonability"]],
        ["recidivous",        ["recidivistic"]],
        ["propulsive",        ["propulsory"]],
        ["recriminatory",     ["recriminative"]],
        ["recruitment",       ["recruital"]],
        ["recurrence",        ["recurrency"]],
        ["recusal",           ["recusement"]],
        ["recusal",           ["recusation"]],
        ["recusancy",         ["recusance"]],
        ["redemptive",        ["redemptory"]],
        ["referable",         ["referrable"]],
        ["referable",         ["referrible"]],
        ["refutative",        ["refutatory"]],
        ["remission",         ["remittal"]],
        ["remittance",        ["remitment"]],
        ["renounceable",      ["renunciable"]],
        ["renunciation",      ["renouncement"]],
        ["reparative",        ["reparatory"]],
        ["repudiatory",       ["repudiative"]],
        ["requital",          ["requitement"]],
        ["rescission",        ["rescindment"]],
        ["restoration",       ["restoral"]],
        ["reticence",         ["reticency"]],
        ["review",            ["reviewal"]],
        ["revision",          ["revisal"]],
        ["revisionary",       ["revisional"]],
        ["revocable",         ["revokable", "revokeable"]],
        ["retributive",       ["retributional", "retributionary"]],
        ["salience",          ["saliency"]],
        ["salutary",          ["salutiferous"]],
        ["sensory",           ["sensatory"]],
        ["sessional",         ["sessionary"]],
        ["shareholder",       ["shareowner"]],
        ["sickly",            ["sicklily"]],
        ["signatory",         ["signator"]],
        ["slander",           ["slanderize"]],
        ["societal",          ["societary"]],
        ["sodomite",          ["sodomist"]],
        ["solicit",           ["solicitate"]],
        ["speculative",       ["speculatory"]],
        ["spirituous",        ["spiritous"]],
        ["statutory",         ["statutorial"]],
        ["submersible",       ["submergeable"]],
        ["submission",        ["submittal"]],
        ["subtle",            ["subtile"]],
        ["sufficiency",       ["sufficience"]],
        ["supplicant",        ["suppliant"]],
        ["succubus",          ["succuba"]],
        ["transposition",     ["transposal"]],
        ["unsolvable",        ["insolvable"]],
        ["surmise",           ["surmisal"]],
        ["suspendable",       ["suspendible"]],
        ["synthesize",        ["synthetize"]],
        ["systematize",       ["systemize"]],
        ["tactile",           ["tactual"]],
        ["tangential",        ["tangental"]],
        ["tautological",      ["tautologous"]],
        ["thenceforth",       ["thenceforward"]],
        ["transience",        ["transiency"]],
        ["transposition",     ["transposal"]],
        ["T-shirt",           ["tee-shirt"]],
        ["unalterable",       ["inalterable"]],
        ["uncommunicative",   ["incommunicative"]],
        ["uncontrollable",    ["incontrollable"]],
        ["unenforceable",     ["nonenforceable"]],
        ["unnavigable",       ["innavigable"]],
        ["unreasonableness",  ["unreasonability"]],
        ["usurpation",        ["usurpature"]],
        ["variational",       ["variative"]],
        ["vegetative",        ["vegetive"]],
        ["vindictive",        ["vindicative"]],
        ["vituperative",      ["vituperous"]],
        ["vociferous",        ["vociferant"]],
        ["volitional",        ["volitive"]],
        ["wolverine",         ["wolverene"]],
        ["wolfish",           ["wolvish"]],
        ["Zoroastrianism",    ["Zoroastrism"]],
    ]

    return preferred_forms_check(blob, preferences, err, msg)
