"""Redundancy."""

from __future__ import annotations

from proselint.checks import Pd, preferred_forms_check3_conv, preferred_forms_check3
from proselint.checks import ResultCheck
from proselint.checks import preferred_forms_check

examples_pass = [
    "Smoke phrase with nothing flagged.",
]

examples_fail = [
    "The table was rectangular in shape.",
    "It was blatantly obvious what to do next.",
    "Taking the package was absolutely essential.",
    "He often repeated the old adage.",
    "So much stuff and etc.",
    "Associate together in groups.",
]


def check(text: str) -> list[ResultCheck]:
    """Suggest the preferred forms."""
    err = "redundancy.wallace"
    msg = "Redundancy. Use '{}' instead of '{}'."

    redundancies = [
        ["rectangular", ["rectangular in shape"]],
        ["audible", ["audible to the ear"]],
    ]
    return preferred_forms_check(text, redundancies, err, msg)


def check_garner(text: str) -> list[ResultCheck]:
    """Suggest the preferred forms.

    source:     Garner's Modern American Usage
    source_url: http://bit.ly/1T4alrY
    """
    err = "redundancy.garner"
    msg = "Redundancy. Use '{}' instead of '{}'."

    redundancies = [
        ["adequate", ["adequate enough"]],
        ["admitted", ["self-admitted"]],
        ["affidavit", ["sworn affidavit"]],
        ["agreement", ["mutual agreement"]],
        ["alumnus", ["former alumnus"]],
        ["antithetical", ["directly antithetical"]],
        ["approximately", ["approximately about"]],
        ["associate", [r"associate together(?: in groups)?"]],
        ["bivouac", ["temporary bivouac", "bivouac camp"]],
        ["blend", ["blend together"]],
        ["but", ["but nevertheless"]],
        ["charged with...", ["accused of a charge"]],
        ["circumstances of", ["circumstances surrounding"]],
        ["circumstances", ["surrounding circumstances"]],
        ["close", ["close proximity"]],
        ["collaborate", ["collaborate together"]],
        ["collaborator", ["fellow collaborator"]],
        ["collaborators", ["fellow collaborators"]],
        ["collocated", ["collocated together"]],
        ["colleagues", ["fellow colleagues"]],
        ["combine", ["combine together"]],
        ["complacent", ["self-complacent"]],
        ["confessed", ["self-confessed"]],
        ["connect", ["connect together"]],
        ["consensus", ["(?:general )?consensus of opinion"]],
        ["consolidate", ["consolidate together"]],
        ["continues to", ["still continues to"]],
        ["contradictory", ["mutually contradictory"]],
        ["cooperation", ["mutual cooperation"]],
        ["couple", ["couple together"]],
        ["crisis", ["serious crisis"]],
        ["eliminate", ["entirely eliminate"]],
        ["especially", ["most especially"]],
        ["fact", ["actual fact"]],
        ["facts", ["true facts"]],
        ["forecast", ["future forecast"]],
        ["founding fathers", ["founding forefathers"]],
        ["free", ["free and gratis"]],
        ["free", ["free gratis"]],
        ["full", ["completely full"]],
        ["fundamentals", ["basic fundamentals"]],
        ["gift", ["free gift"]],
        ["innovation", ["new innovation"]],
        ["interact", ["interact with each other"]],
        ["large", ["large-size"]],
        ["meld", ["meld together"]],
        ["merge", ["merge together"]],
        ["mingle", ["mingle together"]],
        ["mix", ["mix together"]],
        ["mutual feelings", ["mutual feelings for eachother"]],
        ["mutual respect", ["mutual respect for each other"]],
        ["native citizen", ["native-born citizen"]],
        ["necessity", ["absolute necessity"]],
        ["obvious", ["blatantly obvious"]],
        ["pause", ["pause for a moment"]],
        ["planning", ["advance planning"]],
        ["plans", ["future plans"]],
        ["pooled", ["pooled together"]],
        ["potable water", ["potable drinking water"]],
        ["potable water", ["potable drinking water"]],
        ["recruit", ["new recruit"]],
        ["reelected", ["reelected for another term"]],
        ["refer", ["refer back"]],
        ["regress", ["regress back"]],
        ["repay them", ["repay them back"]],
        ["repay", ["repay back"]],
        ["repeat", ["repeat again"]],
        ["repeat", ["repeat back"]],
        ["repeat", ["repeat the same"]],
        ["repeated", ["repeated the same"]],
        ["reprieve", ["temporary reprieve"]],
        ["respite", ["brief respite"]],
        ["retirement", ["retiral", "retiracy"]],
        ["retreat", ["retreat back"]],
        ["return", ["return back"]],
        ["scrutinize", ["closely scrutinize"]],
        ["software", ["software program"]],
        ["surrounded", ["surrounded on all sides"]],
        ["the nation", ["the whole entire nation"]],
        ["throughout the", ["throughout the entire"]],
        ["timpani", ["timpani drum"]],
        ["twins", ["pair of twins"]],
        ["vacancy", ["unfilled vacancy"]],
        ["various", ["various different"]],
        ["veteran", ["former veteran"]],
        ["visible", ["visible to the eye"]],
        ["vocation", ["professional vocation"]],
        ["while", ["while at the same time"]],
    ]

    return preferred_forms_check(text, redundancies, err, msg)


def check_nordquist(text: str) -> list[ResultCheck]:
    """Suggest the preferred forms.

    source:     Richard Nordquist
    source_url: http://grammar.about.com/bio/Richard-Nordquist-22176.htm
    """
    err = "redundancy.nordquist"
    msg = "Redundancy. Use '{}' instead of '{}'."

    redundancies = [
        ["essential", ["absolutely essential"]],
        ["necessary", ["absolutely necessary"]],
        ["a.m.", ["a.m. in the morning"]],
        ["p.m.", ["p.m. at night"]],
    ]
    return preferred_forms_check(text, redundancies, err, msg)


def check_atd_1(text: str) -> list[ResultCheck]:
    """Check for redundancies from After the Deadline.

    NOTE: this was one of the slowest Checks,
          so it was segmented to even the load for parallelization
    """
    err = "redundancy.after_the_deadline"
    msg = "Redundancy. Use '{}' instead of '{}'."

    redundancies = [
        ["Bō", ["Bo Staff"]],
        ["Challah", ["Challah bread"]],
        ["Hallah", ["Hallah bread"]],
        ["Challah", ["Challah bread"]],
        ["I", ["I myself", "I personally"]],
        ["Mount Fuji", ["Mount Fujiyama"]],
        ["Milky Way", ["Milky Way galaxy"]],
        ["Rio Grande", ["Rio Grande river"]],
        ["adage", ["old adage"]],
        ["add", ["add a further", "add an additional"]],
        ["advance", ["advance forward"]],
        ["alternative", ["alternative choice"]],
        ["amaretto", ["amaretto almond"]],
        ["annihilate", ["completely annihilate"]],
        ["anniversary", ["annual anniversary"]],
        ["anonymous", ["unnamed anonymous"]],
        ["as", ["equally as"]],
        ["ascend", ["ascend up"]],
        ["ask", ["ask the question"]],
        ["assemble", ["assemble together"]],
        ["at present the", ["at the present time the"]],
        ["at this point", ["at this point in time"]],
        ["attach", ["attach together"]],
        ["autumn", ["autumn season"]],
        ["bald", ["bald-headed"]],
        ["balsa", ["balsa wood"]],
        ["belongings", ["personal belongings"]],
        ["benefits", ["desirable benefits"]],
        ["bento", ["bento box"]],
        ["best", ["best ever"]],
        ["bit", ["tiny bit"]],
        ["blend", ["blend together"]],
        ["bond", ["common bond"]],
        ["bonus", ["added bonus", "extra bonus"]],
        ["bouquet", ["bouquet of flowers"]],
        ["breakthrough", ["major breakthrough"]],
        ["bride", ["new bride"]],
        ["brief", ["brief in duration"]],
        ["bruin", ["bruin bear"]],
        ["hot", ["burning hot"]],
        ["cacophony", ["cacophony of sound"]],
        ["cameo", ["brief cameo", "cameo appearance"]],
        ["cancel", ["cancel out"]],
        ["cash", ["cash money"]],
        ["chai", ["chai tea"]],
        ["chance", ["random chance"]],
        ["charm", ["personal charm"]],
        ["circle", ["circle around", "round circle"]],
        ["circulate", ["circulate around"]],
        ["classify", ["classify into groups"]],
        ["classmates", ["fellow classmates"]],
        ["cliche", ["old cliche", "overused cliche"]],
        ["climb", ["climb up"]],
        ["clock", ["time clock"]],
        ["collaborate", ["collaborate together"]],
        ["collaboration", ["joint collaboration"]],
        ["colleague", ["fellow colleague"]],
        ["combine", ["combine together"]],
        ["commute", ["commute back and forth"]],
        ["compete", ["compete with each other"]],
        ["comprise", ["comprise of"]],
        ["comprises", ["comprises of"]],
        ["conceived", ["first conceived"]],
        ["conclusion", ["final conclusion"]],
        ["confer", ["confer together"]],
        ["confrontation", ["direct confrontation"]],
        # ["confused",          ["confused state"]],
        ["connect", ["connect together", "connect up"]],
        ["consensus", ["consensus of opinion", "general consensus"]],
        ["consult", ["consult with"]],
        ["conversation", ["oral conversation"]],
        ["cool", ["cool down"]],
        ["cooperate", ["cooperate together"]],
        ["cooperation", ["mutual cooperation"]],
        ["copy", ["duplicate copy"]],
        ["core", ["inner core"]],
        ["cost", ["cost the sum of"]],
        ["could", ["could possibly"]],
        ["coupon", ["money-saving coupon"]],
        ["created", ["originally created"]],
        ["crisis", ["crisis situation"]],
        ["crouch", ["crouch down"]],
        ["currently", ["now currently"]],
        ["custom", ["old custom", "usual custom"]],
        ["danger", ["serious danger"]],
        ["dates", ["dates back"]],
        ["decision", ["definite decision"]],
        ["depreciate", ["depreciate in value"]],
        ["descend", ["descend down"]],
        ["destroy", ["totally destroy"]],
        ["destroyed", ["completely destroyed"]],
        ["destruction", ["total destruction"]],
        ["details", ["specific details"]],
        ["dilemma", ["difficult dilemma"]],
        ["disappear", ["disappear from sight"]],
        ["discovered", ["originally discovered"]],
        ["dive", ["dive down"]],
        ["done", ["over and done with"]],
        ["drawing", ["illustrated drawing"]],
        ["drop", ["drop down"]],
        ["dune", ["sand dune"]],
        ["during", ["during the course of"]],
        ["dwindle", ["dwindle down"]],
        ["dwindled", ["dwindled down"]],
        ["every", ["each and every"]],
        ["earlier", ["earlier in time"]],
        [
            "eliminate",
            [
                "completely eliminate",
                "eliminate altogether",
                "entirely eliminate",
            ],
        ],
        ["ember", ["glowing ember"]],
        ["embers", ["burning embers"]],
        ["emergency", ["emergency situation", "unexpected emergency"]],
        ["empty", ["empty out"]],
        ["enclosed", ["enclosed herein"]],
        ["end", ["final end"]],
        ["engulfed", ["completely engulfed"]],
        ["enter", ["enter in", "enter into"]],
        ["equal", ["equal to one another"]],
        ["eradicate", ["eradicate completely"]],
        ["essential", ["absolutely essential"]],
        [
            "estimated at",
            [
                "estimated at about",
                "estimated at approximately",
                "estimated at around",
            ],
        ],
        ["evolve", ["evolve over time"]],
        ["exaggerate", ["over exaggerate"]],
        ["exited", ["exited from"]],
        ["experience", ["actual experience", "past experience"]],
        ["experts", ["knowledgeable experts"]],
        ["extradite", ["extradite back"]],
        ["face the consequences", ["face up to the consequences"]],
        ["face the fact", ["face up to the fact"]],
        ["face the challenge", ["face up to the challenge"]],
        ["face the problem", ["face up to the problem"]],
        ["facilitate", ["facilitate easier"]],
        ["fact", ["established fact"]],
        ["facts", ["actual facts", "hard facts", "true facts"]],
        ["fad", ["passing fad"]],
        ["fall", ["fall down"]],
        ["fall", ["fall season"]],
        ["feat", ["major feat"]],
        ["feel", ["feel inside"]],
        ["feelings", ["inner feelings"]],
        ["few", ["few in number"]],
        ["filled", ["completely filled", "filled to capacity"]],
        ["first", ["first of all"]],
        ["first time", ["first time ever"]],
        ["fist", ["closed fist"]],
        ["fly", ["fly through the air"]],
        ["focus", ["focus in", "main focus"]],
        ["follow", ["follow after"]],
        ["for example", ["as for example"]],
        # ["foremost",          ["first and foremost"]],
        ["forever", ["forever and ever"]],
        ["free", ["for free"]],
        ["friend", ["personal friend"]],
        ["friendship", ["personal friendship"]],
        ["full", ["full to capacity"]],
        ["fundamentals", ["basic fundamentals"]],
        ["fuse", ["fuse together"]],
        ["gather", ["gather together", "gather up"]],
        ["get up", ["get up on his feet", "get up on your feet"]],
        ["gift", ["free gift"]],
        ["gifts", ["free gifts"]],
        ["goal", ["ultimate goal"]],
        # ["graduate",          ["former graduate"]],
        ["grow", ["grow in size"]],
        ["guarantee", ["absolute guarantee"]],
        ["gunman", ["armed gunman"]],
        ["gunmen", ["armed gunmen"]],
        ["habitat", ["native habitat"]],
        ["had done", ["had done previously"]],
        ["halves", ["two equal halves"]],
        # ["has",               ["has got"]],
        # ["have",              ["have got"]],
        ["haven", ["safe haven"]],
        # ["he",                ["he himself"]],
        ["heat", ["heat up"]],
        ["history", ["past history"]],
        ["hoist", ["hoist up"]],
        ["hole", ["empty hole"]],
        ["honcho", ["head honcho"]],
    ]
    return preferred_forms_check(text, redundancies, err, msg)


def check_atd_2(text: str) -> list[ResultCheck]:
    """Check for redundancies from After the Deadline.

    NOTE: this was one of the slowest Checks,
      so it was segmented to even the load for parallelization
    """
    err = "redundancy.after_the_deadline"
    msg = "Redundancy. Use '{}' instead of '{}'."

    items = {
        "12 noon": "noon",
        "12 o'clock noon": "noon",
        "absolutely necessary": "necessary",
        "absolutely sure": "sure",
        "advance planning": "planning",
        "advance preview": "preview",
        "advance reservations": "reservations",
        "advance warning": "warning",
        "affirmative yes": "yes",
        "all inclusive": "inclusive",
        "anonymous stranger": "stranger",
        "artificial prosthesis": "prosthesis",
        #"bare naked": "naked",
        "boat marina": "marina",
        "brief moment": "moment",
        "careful scrutiny": "scrutiny",
        #"close proximity": "proximity",
        "close scrutiny": "scrutiny",
        "complete monopoly": "monopoly",
        "completely surround": "surround",
        "constantly maintained": "maintained",
        "continue to remain": "remain",
        "exact opposite": "opposite",
        "exact opposites": "opposites",
        "exact replica": "replica",
        "exact same": "same",
        "exposed opening": "opening",
        "final outcome": "outcome",
        "final ultimatum": "ultimatum",
        "foreign imports": "imports",
        "former veteran": "veteran",
        "forward planning": "planning",
        "frozen ice": "ice",
        "frozen tundra": "tundra",
        "full satisfaction": "satisfaction",
        "future plan": "plan",
        "future plans": "plans",
        "future recurrence": "recurrence",
        "harmful injuries": "injuries",
        "high noon": "noon",
        #"highly relevant": "relevant",
        "honest truth": "truth",
        "hot water heater": "water heater",
        "in actual fact": "in fact",
        "in which we live in": "in which we live",
        "incredible to believe": "incredible",
        #"indicted on a charge": "indicted",
        "innovative new": "innovative",
        #"input into": "input",
        "integrate together": "integrate",
        "integrate with each other": "integrate",
        "interdependent on each other": "interdependent",
        "introduced for the first time": "introduced",
        "kneel down": "kneel",
        "knots per hour": "knots",
        #"last of all": "last",
        #"later time": "later",
        "lift up": "lift",
        "live studio audience": "studio audience",
        "live witness": "witness",
        "look ahead to the future": "look to the future",
        "manually by hand": "manually",
        "may possibly": "may",
        "meet together": "meet",
        "meet with each other": "meet",
        "mental telepathy": "telepathy",
        "merge together": "merge",
        "merged together": "merged",
        "meshed together": "meshed",
        "migraine headache": "migraine",
        "minestrone soup": "minestrone",
        "mix together": "mix",
        "moment in time": "moment",
        "mutual respect for each other": "mutual respect",
        "mutually dependent on each other": "mutually dependent",
        "mutually interdependent": "interdependent",
        "my personal opinion": "my opinion",
        "nape of her neck": "nape",
        "natural instinct": "instinct",
        "naturally instinct": "instinct",
        #"necessary requirements": "requirements",
        "never at any time": "never",
        "new innovation": "innovation",
        "new innovative": "innovative",
        "new invention": "invention",
        "nostalgia for the past": "nostalgia",
        "now pending": "pending",
        "number of different": "number of",
        "old pioneer": "pioneer",
        "old proverb": "proverb",
        "open trench": "trench",
        "orbits around": "orbits",
        "outside in the yard": "in the yard",
        "past memories": "memories",
        "penetrate through": "penetrate",
        "perfect ideal": "ideal",
        "plan ahead": "plan",
        "plan in advance": "plan",
        "point in time": "point",
        "polar opposite": "opposite",
        "polar opposites": "opposites",
        "positive identification": "identification",
        "postpone until later": "postpone",
        "pouring down rain": "pouring rain",
        "precise same": "same",
        "present incumbent": "incumbent",
        "previously listed above": "previously listed",
        "private industry": "industry",
        "probed into": "probed",
        "proceed ahead": "proceed",
        "proposed plan": "plan",
        #"protrude out": "protrude",
        "put off until later": "put off",
        #"raise up": "raise",
        "rate of speed": "speed",
        "re-elect for another term": "re-elect",
        "reason is because": "reason is",
        "recur again": "recur",
        "refer back": "refer",
        "reflect back": "reflect",
        "reply back": "reply",
        "retreat back": "retreat",
        "revert back": "revert",
        "rough rule of thumb": "rule of thumb",
        "round in shape": "round",
        "rustic country": "rustic",
        "safe sanctuary": "sanctuary",
        "same exact": "same",
        "same identical": "identical",
        "scrutinize in detail": "scrutinize",
        "secret that cannot be told": "secret",
        "seek to find": "seek",
        "separated apart from each other": "separated",
        "share together": "share",
        "sharp point": "point",
        "shiny in appearance": "shiny",
        "sink down": "sink",
        "skipped over": "skipped",
        #"slow speed": "slow",
        #"small size": "small",
        "small speck": "speck",
        "soft in texture": "soft",
        "soft to the touch": "soft",
        "sole of the foot": "sole",
        "some time to come": "some time",
        "spell out in detail": "spell out",
        "spiked upward": "spiked",
        "spiked upwards": "spiked",
        "spring season": "spring",
        "still lingers": "lingers",
        "still persists": "persists",
        "still remains": "remains",
        "sudden impulse": "impulse",
        "sufficient enough": "sufficient",
        "summer season": "summer",
        "surrounded on all sides": "surrounded",
        "tall in height": "tall",
        "tall in stature": "tall",
        "ten in number": "ten",
        "these ones": "these",
        #"they themselves": "they",
        "those ones": "those",
        "three-way love triangle": "love triangle",
        "truly sincere": "sincere",
        "twelve midnight": "midnight",
        "twelve noon": "noon",
        "unconfirmed rumor": "rumor",
        #"undeniable truth": "undeniable",
        "undergraduate student": "undergraduate",
        "underground subway": "subway",
        "unexpected surprise": "surprise",
        #"unintentional mistake": "unintentional",
        "universal panacea": "panacea",
        "unsolved mystery": "mystery",
        "vacillate back and forth": "vacillate",
        "visible to the eye": "visible",
        "wall mural": "mural",
        "warn in advance": "warn",
        "winter season": "winter",
        "yakitori chicken": "yakitori",
        "yerba mate tea": "yerba mate",
    }

    return preferred_forms_check3(text, items, err, msg)


def check_atd_special(text: str) -> list[ResultCheck]:
    """Check for redundancies from After the Deadline.

    NOTE: this was one of the slowest Checks,
      so it was segmented to even the load for parallelization
    """
    err = "redundancy.after_the_deadline"
    msg = "Redundancy. Use '{}' instead of '{}'."
    items = {r"\band etc\.": "etc."}

    return preferred_forms_check3(text, items, err, msg, padding=Pd.disabled)
